using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SourceGenerator.Helper.CopyCode.IntegrationTests;
[TestClass]
public class CopyGeneratorIntegrationTests {
    [TestMethod]
    public void Generated_HelloWorld() {
        string greeting = CopyCode.Copy.SourceGeneratorHelperCopyCodeIntegrationTestsGreeter;

        Assert.AreEqual("""
				// <auto-generated/>
				#nullable enable

				namespace SourceGenerator.Helper.CopyCode.IntegrationTests;
				internal static partial class Greeter
				{
				    public static void GetHelloWorld()
				    {
				    }
				}
				""", greeting);
    }
}
[CopyCode.Copy]
internal static partial class Greeter {
    public static void GetHelloWorld() { }
}
